### ISSUE TITLE
REST-Fuuu - Rest e a polícia do HTTP

### ISSUE THREAD

**Issue by igorsantos07** [PHPRio/cpf#118]
Título: **REST-Fuuu - Rest e a polícia do HTTP**
Palavras-chave: `HTTP`, `REST`, `API`, `RESTful`
Nível: **intermediário**
Palestrante: [**Igor Santos**](#117)
Descrição da palestra:
> Descrição dos principais pontos que fazem uma API REST ser RESTful, incluindo detalhes básicos sobre como o HTTP funciona, seus verbos, códigos de erro, entre outros.

[Slides](https://speakerdeck.com/igorsantos07/rest-fuuu-front-end)

**Comment by igorsantos07** [comment]
Palestra antiga (portando da página antiga de palestras do site), apresentada no [SENAC Santa Luzia em 27/10/2016](https://www.meetup.com/PHP-Rio/events/234774958/)

**Comment by lhsazevedo** [comment]
Queria assistir essa aqui
