### ISSUE TITLE
PHP, uma das linguagens de desenvolvimento mais populares

### ISSUE THREAD

**Issue by thiagoluna** [PHPRio/cpf#120]
Título: **PHP, uma das linguagens de desenvolvimento mais populares**
Palavras-chave: `php`, `backend`
Nível: **básico**
Palestrante: [**Thiago Luna**](número da issue com dados do palestrante)
Email: thiagoluna2@gmail.com
LinkedIn: [thiago-luna](https://www.linkedin.com/in/thiago-luna/)
GitHub: [thiagoluna](https://github.com/thiagoluna)
Descrição da palestra:
> Nesta palestra apresento o resultado de uma pesquisa feita pelo site W3Techs, que mostra o percentual de uso de várias linguagens de programação server-side e aponta o PHP como o mais usado dentro de um universo de 10 milhões de sites pesquisados.

[Slides](https://docs.google.com/presentation/d/15NuMB99oTBTtff4lOFRQuiSgJtK4VuZbCvkn7Am8CPM/edit?usp=sharing)

**Comment by DaianeAlvesRJ** [comment]
Palestra realizada no evento do dia 23/10/2019
Link para o evento: https://www.meetup.com/pt-BR/PHP-Rio/events/tgljxpyznbgc/
