### ISSUE TITLE
Deploy de Aplicação Laravel com Kubernetes

### ISSUE THREAD

**Issue by diogomascarenha** [PHPRio/cpf#124]
Título: **Deploy de Aplicação Laravel com Kubernetes**
Palavras-chave: `laravel`, `kubernetes`, `php`, `devops`, `googlecloud`
Nível: **Intermediário**
Palestrante: [**Diogo Mascarenhas**](https://github.com/PHPRio/CFP/issues/123)
Slides: https://slides.com/diogooliveiramascarenhas/deploy-laravel-kubernetes
Descrição da palestra:
> Vamos aprender como efetuar o deploy de uma aplicação desenvolvida em PHP/Laravel no Google Cloud utilizando Docker e Kubernetes.

**Comment by CViniciusSDias** [comment]
Palestra apresentada no meetup do dia 12/03/2020

**Comment by leogomesdev** [comment]
Olá @diogomascarenha, tudo bem?
Gostei muito da palestra, parabéns!
Você poderia disponibilizar os slides ou o repositório?

Procuro especificamente o Dockerfile com duas "images", a primeira só pra rodar o composer e a segunda pra usar a "vendor" criada e então continuar o build da aplicação, sem o composer.

(Não encontrei nesse repo [https://github.com/diogomascarenha/app-palestra-laravel-k8s](https://github.com/diogomascarenha/app-palestra-laravel-k8s))

Obrigado desde já :)

**Comment by diogomascarenha** [comment]
Olá @leogomezzz!

  Adicionei o link da palestra e dentro dela tem a explicação linha a linha do Dockerfile utilizado.

Um abraço!
