### ISSUE TITLE
Boas práticas de segurança em aplicações Laravel

### ISSUE THREAD

**Issue by raphaeldealmeida** [PHPRio/cpf#125]
Título: **Boas práticas de segurança em aplicações Laravel**
Palavras-chave: `segurança`, `laravel`
Nível: **básico**
Palestrante: [**Raphael de Almeida**](43)
Descrição da palestra:
> Apresentar conceitos de segurança em aplicações web e como elas podem ser utilizadas no Laravel.

[Slides](https://speakerdeck.com/raphaeldealmeida/boas-praticas-de-seguranca-em-aplicacoes-laravel)

**Comment by CViniciusSDias** [comment]
Palestra apresentada no meetup do dia 12/03/2020
