### ISSUE TITLE
Métricas de código - Vendo o tamanho da M

### ISSUE THREAD

**Issue by CViniciusSDias** [PHPRio/cpf#128]
Título: **Métricas de código - Vendo o tamanho da M**
Palavras-chave: `qualidade`, `oo`, `métricas`
Nível: **intermediário**
Palestrante: [Vinicius Dias](https://github.com/PHPRio/CFP/issues/38) 
Descrição da palestra:

> Antes de tomar uma decisão de negócio, empresários sempre olham gráficos, relatórios, etc. Até deram um nome bonito pra isso: BI.
> 
> E antes de uma equipe de desenvolvimento tomar uma decisão? O que olhamos? Vamos no chute?
> 
> Nesta palestra vamos falar o que pode ser chamado de Software Intelligence, ou apenas métricas de código.
> 
> Como saber o que refatorar primeiro? Qual módulo / classe parece estar mais complexo? Métricas podem responder perguntas valiosas com estas, e são mega fáceis de gerar.
> 
> Além de ferramentas para gerar métricas, vamos falar sobre estratégias de geração de métricas e algumas já muito conhecidas no mercado.

**Comment by vitormattos** [comment]
Não vai fazer mais esta talk algum dia?! A proposta é maneira.

**Comment by CViniciusSDias** [comment]
> Não vai fazer mais esta talk algum dia?! A proposta é maneira.

Eu já não estudo o assunto há algum tempo e estou desatualizado nas ferramentas do momento. Como tenho outras propostas para escrever, vou deixar essa "inativa" por enquanto. Mas no futuro, quem sabe eu não retomo a ideia e reabro a issue, né!?
