### ISSUE TITLE
Como configurar o vsCode para o desenvolvimento em PHP

### ISSUE THREAD

**Issue by dancbatista** [PHPRio/cpf#134]
Título: Como configurar o vsCode para o desenvolvimento em PHP
Palavras-chave: php, vsCode, psr
Nível: iniciante
Palestrante: Daniel Cleber Batista 133
Descrição da palestra:

Adição e configuração dos plugins PHP Debug,  PHP Intelephense,  PHP CodeSniffer e Prettier para desenvolvimento PHP no vsCode.

**Comment by vitormattos** [comment]
@dancbatista dá um confere na formatação de outras issues, tem umas formatações de markdown.

**Comment by CViniciusSDias** [comment]
@dancbatista , topa apresentar essa talk dia 09 de setembro agora?
:-)

**Comment by DaianeAlvesRJ** [comment]
@dancbatista consegue apresentar essa talk no dia 27/05 pra nós?

**Comment by dancbatista** [comment]
Daiane, tudo bem? DIa 27 eu estou em lua de mel. acabei de me casar. A
partir do dia 02/06. Tudo bem!

Em ter., 17 de mai. de 2022 às 11:53, Daiane Alves ***@***.***>
escreveu:

**Comment by DaianeAlvesRJ** [comment]
Ótima notícia. Parabéns ao casal. ;-)
Vamos então tentar no dia 24/06?

**Comment by dancbatista** [comment]
Pode ser sim! Excelente!

Em ter., 17 de mai. de 2022 às 12:41, Daiane Alves ***@***.***>
escreveu:

**Comment by DaianeAlvesRJ** [comment]
Maravilha, vou anunciar então no meetup de amanhã pro pessoal já reservar essa data.
Qualquer coisa, dá um oi lá na comunidade do Telegram.
Obrigada!!!

**Comment by DaianeAlvesRJ** [comment]
Oi, @dancbatista tudo certo pra sua palestra na próxima semana (dia 24/06)?
Começamos a divulgação, se precisar de qualquer coisa, chama lá no grupo do Telegram ;-)

**Comment by DaianeAlvesRJ** [comment]
Houve um imprevisto com o palestrante e ele não pode comparecer no dia marcado para palestrar.
