### ISSUE TITLE
🧵 Strings e bytes: manipulando dados binários com PHP

### ISSUE THREAD

**Issue by lhsazevedo** [PHPRio/cpf#135]
Título: **🧵 Strings e bytes: manipulando dados binários com PHP**
Palavras-chave: `string`, `byte`, `binário`
Nível: **básico**
Palestrante: [Lucas Azevedo](#132)
Descrição da palestra:
> String binária? Entenda a relação de cadeias de caracteres e bytes no PHP.

*Slides em breve*
*Repositório em breve*

**Comment by vitormattos** [comment]
Apresentado em meetup online no dia 09/10/2021
