### ISSUE TITLE
Como criar uma RESTful API usando Laravel Lumen

### ISSUE THREAD

**Issue by miriam128** [PHPRio/cpf#141]
Título: **Como criar uma RESTful API usando Laravel Lumen**
Palavras-chave: `laravel`, `lumen`, `back-end`
Nível: **iniciante**
Palestrante: [**Miriam Amaral**](140)
Descrição da palestra:

> Você conhece o Laravel Lumen? Sabe o porquê ele foi criado? Qual o futuro do Laravel Lumen?
 Nesta palestra vamos realizar uma breve revisão da criação e existência do Laravel Lumen, os primeiros passos para a configuração do ambiente de desenvolvimento do micro-framework, criar uma API usando Laravel Lumen, Laragon e Insomnia e falar sobre o que acontecerá com o Laravel Lumen após a versão 9.0.0.

**Comment by DaianeAlvesRJ** [comment]
Palestra apresentada no evento realizado no dia 27/05/2022 (https://www.meetup.com/pt-BR/php-rio/events/286035402/)
