### ISSUE TITLE
Processo de construção de uma rede neural

### ISSUE THREAD

**Issue by MarGraco** [PHPRio/cpf#149]
Título: **Processo de construção de uma rede neural**
Palavras-chave: `Machine Learning`, `Neural Networks`, `Redes Neurais`
Nível: **intermediário**
Palestrante: [**Marcello Graco Bispo Magalhães Nogueira**](148)
Descrição da palestra:
> Funcionamento de uma rede neural. Arquiteturas de neurais. Funções de Ativação. Preparação de um dataset e utilizando para treinamento da rede neural através do google colab. Deploy em nuvem. Integração com APIs e suas ferramentas.

[Slides](https://www.canva.com/design/DAFMuV4kA8s/PX-p8fjF7_Ocp3uN-28v2g/view)

**Comment by lhsazevedo** [comment]
Palestra apresentada no dia 28/08/2022.
