### ISSUE TITLE
Modelando com Maestria: A Arte de Relacionamentos no Laravel

### ISSUE THREAD

**Issue by aeusteixeira** [PHPRio/cpf#185]
Título: **Modelando com Maestria: A Arte de Relacionamentos no Laravel**
Palavras-chave: `Laravel`, `Eloquent`, `Relacionamentos`, `Models`
Nível: **Intermediário**
Palestrante: [**Matheus Teixeira**](https://github.com/PHPRio/CFP/issues/185)
Descrição da palestra:
> Nesta palestra, exploraremos a arte de modelar relacionamentos no Laravel utilizando o Eloquent ORM. Abordaremos desde os conceitos básicos até técnicas avançadas para criar e gerenciar relações entre modelos de forma eficiente e elegante. Aprenda a dominar um para um, um para muitos, muitos para muitos e outros tipos de relacionamentos, além de dicas práticas para otimizar consultas e manter seu código limpo e organizado

**Comment by DaianeAlvesRJ** [comment]
Palestra apresentada no meetup do dia 23/02 na Le Wagon
https://www.meetup.com/pt-BR/php-rio/events/299255912/
