### ISSUE TITLE
O código por trás da Wikipedia, conhecendo melhor o projeto MediaWiki

### ISSUE THREAD

**Issue by liviacarolgouvea** [PHPRio/cpf#187]
Título: **O código por trás da Wikipedia, conhecendo melhor o projeto MediaWiki**
Palavras-chave: `MediaWiki`, `PHP`, `opensource`, `LAMP`
Nível: **médio**
Palestrante: [Lívia Gouvêa](https://github.com/PHPRio/CFP/issues/186)
Descrição da palestra:
> Nesta palestra vou mostrar um pouco do projeto MediaWiki, o sistema utilizado na plataforma Wikipedia. 
Vou mostrar um pouco de sua arquitetura, stack de desenvolvimento, instalação, estrutura de repositórios e extensões.

- [Slides](https://slides.com/liviagouvea/mediawiki)

**Comment by DaianeAlvesRJ** [comment]
Palestra apresentada no meetup do dia 23/02 na Le Wagon 
https://www.meetup.com/pt-BR/php-rio/events/299255912/
